#!/bin/sh -e

MINKVER="2.6.24"
PREREQ=""

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/swapon /sbin
copy_exec /sbin/reboot /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /bin/chown /bin
copy_exec /bin/mount /bin
copy_exec /bin/readlink /sbin
copy_exec /usr/bin/adbd /sbin
copy_exec /lib/#DEB_HOST_MULTIARCH#/libz.so.1
copy_exec /lib/#DEB_HOST_MULTIARCH#/libcrypto.so.1.0.0
copy_exec /lib/#DEB_HOST_MULTIARCH#/libdl.so.2
